config/routes.rb
SoccerApp::Application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  scope "/admin" do
    resources :users
    match 'users/:id/delete' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end

  resources :accounts do
    resources :teams
    resources :locations
    get "report" => 'accounts#report', as: :report
  end

  resources :categories do
    resources :tests
  end

  resources :session_plan_categories do
     resources :session_plans
  end

  resources :players 
  
  resources :test do
    resources :scores
  end

  post 'manage_scores' => 'scores#manage', as: :manage_scores
  post 'scores' => 'scores#index', as: :scores
  get 'coach/:id' => 'users#coach_profile', as: :coach
  get 'coach_admin/:id' => 'users#coach_admin_controls', as: :coach_admin
  get 'account_error' => 'users#account_error', as: :account_error
  get 'account_select' => 'users#account_select', as: :account_select
  get '/player/history/:id/:test_id' => 'players#history', as: :player_history
  post '/player/coach_report/' => 'players#coach_report', as: :coach_report
  post '/players/compare_players/' => 'players#compare_players', as: :compare_players
  post '/players/import/' => 'players#import', as: :players_import
  post '/players/search/' => 'players#search', as: :players_search
  get '/player/:id/players_scores' => 'players#players_scores', as: :players_scores

  post 'teams/report' => 'teams#team_report', as: :team_report
  post 'tests/report' => 'tests#tests_report', as: :tests_report

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

validates_presence_of :first_name, :last_name, :email, :type_user

  has_and_belongs_to_many :accounts
  # has_and_belongs_to_many :teams
  # has_many :scores
  # has_many :tests, :through => :scores
  has_many :players

  extend EnumerateIt
  has_enumeration_for :type_user, :with => Role, :create_helpers => true

  scope :coach, lambda{where(:type_user => Role::COACH)}
  scope :standard, lambda{where(:type_user => Role::STANDARD)}
  scope :admin, lambda{where(:type_user => Role::ADMIN)}
#  scope :scores_time, lambda{where("users.id not in (select user_id from accounts_users)")}
  scope :can_see_session_plans, lambda{where(:session_plans_visible => true)}
 
  def full_name
    "#{first_name} #{last_name}".titleize
  end
  
  def has_players?
    players.count > 0
  end
  
  def is_player?
    type_user == 2
  end

  # def age
    # ((DateTime.now - birthday) / 365.25).to_i
  # end
# 
  # def high_time_score(test_id)
    # sql = "select min(to_char(to_timestamp(value) AT TIME ZONE 'UTC','HH24:MI:SS')) as time from scores where user_id = #{id} and test_id = #{test_id}"
    # self.connection.execute(sql).to_a[0]["time"]
  # end
# 
  # def high_numeric_score(test_id)
    # get_score_test(test_id).maximum("value").to_f
  # end
# 
  # def pos_age_rank_numeric(test_id, age)
    # sql = "select * from (SELECT row_number() OVER (order by avg(s.value) DESC) as pos, EXTRACT(year from AGE(NOW(), u.birthday)) as age, u.first_name as name, avg(s.value) as average, t.id as test_id, u.id as user_id from users u, scores s, tests t where s.user_id = u.id and s.test_id = t.id and t.id = #{test_id} and EXTRACT(year from AGE(NOW(), u.birthday)) = #{age} group by u.birthday, u.first_name, t.id, u.id) as h where user_id = #{id};"
    # connection.execute(sql).to_a[0]["pos"]
  # end
# 
  # def pos_age_rank_time(test_id, age)
    # sql = "select * from (SELECT row_number() OVER (order by to_char(to_timestamp(avg(s.value)) AT TIME ZONE 'UTC','HH24:MI:SS') ASC) as pos, EXTRACT(year from AGE(NOW(), u.birthday)) as age, u.first_name as name, to_char(to_timestamp(avg(s.value)) AT TIME ZONE 'UTC','HH24:MI:SS') as average, t.id as test_id, u.id as user_id from users u, scores s, tests t where s.user_id = u.id and s.test_id = t.id and t.id = #{test_id} and EXTRACT(year from AGE(NOW(), u.birthday)) = #{age} group by u.birthday, u.first_name, t.id, u.id) as h where user_id = #{id};"
    # result = connection.execute(sql).to_a[0]["pos"]
  # end
# 
  # def pos_overall_time_rank(test_id)
    # sql = "SELECT * from (SELECT row_number() OVER (order by to_char(to_timestamp(avg(value)) AT TIME ZONE 'UTC','HH24:MI:SS') ASC) as pos, to_char(to_timestamp(avg(value)) AT TIME ZONE 'UTC +4:30','HH24:MI:SS'), user_id from scores where test_id = #{test_id} group by user_id) as h where user_id = #{id};"
    # connection.execute(sql).to_a[0]["pos"]
  # end
# 
  # def pos_overall_numeric_rank(test_id)
    # sql = "SELECT * FROM (SELECT row_number() OVER (order by avg(value) DESC) as pos, avg(value), user_id from scores where test_id = #{test_id} group by user_id) as h where user_id = #{id};"
    # connection.execute(sql).to_a[0]["pos"]
  # end
# 
  # def has_scores?(test_id)
    # get_score_test(test_id).count > 0
  # end
# 
  # def get_score_test(test_id)
    # scores.where("test_id = ?", test_id)
  # end
# 
  # def average_scores(test_id)
    # get_score_test(test_id).average(:value)
  # end
# 
  # def user_for_age
    # sql = "SELECT * FROM (SELECT EXTRACT(year from AGE(NOW(), birthday)) as age from users) as h where age = #{age}"
    # connection.execute(sql).to_a
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :update, :edit]
before_action :charge_teams

	def index
    if current_user.standard?
      @users = User.standard.order(:last_name)
    else
      @users = User.all.order(:type_user).order(:last_name)
    end
	end

	def new
		@user = User.new
	end
	
	def show
    @user = User.find(params[:id])
	end

	def edit
  end

  def update
    if params[:user][:password].blank?
		  params[:user].delete(:password)
		  params[:user].delete(:password_confirmation)
		end

    if @user.update(user_params)
      redirect_to users_url, notice: "User updated successfully."
    else
      render 'edit'
    end
  end

	def create
		@user = User.new(user_params)

    if @user.save
      #NotificationMailer.notification_to_user(@user, params[:user][:password]).deliver
      redirect_to users_url, notice: "User created successfully."
    else
      render 'new'
    end
	end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.players.destroy_all
    @user.destroy
    
    redirect_to users_url, notice: "User deleted."
  end

  def coach_profile
    @account = Account.find(params[:id])
    session[:account] = @account
    @categories = Category.all
    # @players = Player.joins(:teams).where("teams.account_id = ?", session[:account]).order(:first_name)
    # @tests = @categories.first.tests
  end

  def coach_admin_controls
    @account = Account.find(params[:id])
    session[:account] = @account
    @categories = Category.all
    @players = Player.joins(:teams).where("teams.account_id = ?", session[:account]).order(:first_name).uniq
    # @tests = @categories.first.tests
  end
  
private

	def user_params
    params.require(:user).permit(:birthday, :first_name, :last_name, :type_user, :email, :password, :password_confirmation, :session_plans_visible)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def charge_teams
    if current_user.coach?
      @show = "display:none"
      @teams = Team.all.where(account_id: session[:account])
    else
      @teams = Team.all
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
- content_for :head do
  = javascript_include_tag "manage_fields.js"
= form_for @user, :html => { :class => "form-horizontal" } do |f|
  
  - unless @user.errors.empty?
    ul.form-errors
      - @user.errors.full_messages.each do |message|
          li= message
          
  - if current_user.admin?
    .form-group style="#{@show}"
      = label_tag :type_user, "Select user type", :class => 'control-label'
      .controls
        = f.select(:type_user, options_for_select(Role.to_a, selected: f.object.type_user), {prompt: 'Please select your role for the user'}, {class: 'form-control'})
    .form-group
      = label_tag :session_plans_visible, "Are session plans visible for this user?", :class => 'control-label'
      .controls
        = f.check_box :session_plans_visible
  .form-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'form-control'
  .form-group
    = f.label :first_name, :class => 'control-label'
    .controls
      = f.text_field :first_name, :class => 'form-control'
  .form-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'form-control'
  .form-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.text_field :password, :class => 'form-control', type: "password"
  .form-group
    = f.label :password_confirmation, :class => 'control-label'    
    .controls
      = f.text_field :password_confirmation, class: "form-control", type: "password"
  
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/account_error.html.slim
h1.text-center Sorry, you do not have associated accounts
h3.text-center Please contact with your administrator

app/views/users/account_select.html.slim
.row
  .panel.panel-info
    .panel-heading
      h3.panel-title Select Account
    .panel-body
      .list-group
      	-if current_user.admin?
      	  -Account.active.each do |a|
      	    =link_to a.name, coach_path(a.id), class: "list-group-item"
      	-else
          - current_user.accounts.active.each do |a|
          	= link_to a.name, coach_path(a.id), class: "list-group-item"

app/views/users/coach_admin_controls.html.slim
h1 Admin Control Panel
.row
  .col-sm-6
    .well
      h2.text-center
        span.glyphicon.glyphicon-share
        span  Manage Player Score
      hr
      .well
        = form_tag(manage_scores_path, method: 'post', class: "form-horizontal")
          .form-group
            label.col-sm-3.control-label Select Player
            .col-sm-9
              = select_tag "player", options_from_collection_for_select(@players, :id, :full_name), {class: 'form-control chosen-select'}

          .form-group
            label.col-sm-3.control-label Select Test
            .col-sm-9
              select#tests name="tests" class="form-control"
                - @categories.each do |category|
                    optgroup label=(category.name)
                    - category.tests.each do |test|
                        option value="#{test.id}"  #{test.name}

          = button_to "Manage", nil, :class => 'btn btn-primary pull-right'
          .clearfix

  .col-sm-6
    .well
      h2.text-center
        span.glyphicon.glyphicon-list-alt
        span  Review Players Scores
      hr
      .well
        = form_tag(players_search_path, action: 'search', class: "form-horizontal")
          .form-group
            label.col-sm-3.control-label Select Player
            .col-sm-9
              = select_tag "player", options_from_collection_for_select(@players, :id, :full_name), {class: 'form-control chosen-select'}
          hr  
          hr
          = button_to "Review", nil, :class => 'btn btn-primary pull-right'
          .clearfix

.row
  .col-sm-6
    .well
      h2.text-center
        span.glyphicon.glyphicon-plus
        span  Manage Players
      .well
        - 3.times do
          hr
        = link_to new_player_path(@account), class: "btn btn-primary pull-left" do
          span.glyphicon.glyphicon-plus 
          span  Add New Player
        = link_to players_path, class: "btn btn-primary pull-right" do
          span.glyphicon.glyphicon-pencil
          span  Manage Players
        - 4.times do
          hr
          
  .col-sm-6
    .well
      h2.text-center
        span.glyphicon.glyphicon-upload
        span  Import Players
      hr
      .well
        = form_tag(players_import_path, multipart: true, class: "form-horizontal") do
          .form-group 
            label.col-sm-3.control-label Select Teams
            .col-sm-9
              = select_tag :teams, options_from_collection_for_select(@account.teams, :id, :name), class: 'form-control chosen-select', multiple: true, "data-placeholder" => "Please select the Player's Team"

          .form-group
            label.col-sm-3.control-label Select CSV File
            .col-sm-9
              = file_field_tag "csv_players", class: "form-control"

          = button_to "Import", nil, :class => 'btn btn-primary pull-right'
          .clearfix

          

- if current_user.admin?
  .row
    .col-sm-6
      .well
        h2.text-center
          span.glyphicon.glyphicon-th-list
          span  Create Reports
        hr
        .well
          = form_tag(team_report_path, method: 'post', class: "form-horizontal")
            - if flash[:teams]
              .form-group.field_with_errors
                label.col-sm-3.control-label Select Teams
                .col-sm-9
                  = grouped_collection_select(:team, :id, Account.all, :teams, :name, :id, :name, {}, {:class => 'form-control chosen-select', :multiple => true, "data-placeholder" => "Please select the Player's Team"})
                  span class="error"
                    = flash[:teams]

            - else
              .form-group
                label.col-sm-3.control-label Select Teams
                .col-sm-9
                  = grouped_collection_select(:team, :id, Account.all, :teams, :name, :id, :name, {}, {:class => 'form-control chosen-select', :multiple => true, "data-placeholder" => "Please select the Player's Team"})

            .form-group
              label.col-sm-3.control-label Choose Date
              .col-sm-9
                = select_tag "date", options_for_select(['Today', 'Last 7 Days', 'This Month', 'All Time'], params[:date]), {class: 'form-control'}

            .form-group
              label.col-sm-3.control-label Select Test
              .col-sm-9
                select#tests name="tests" class="form-control"
                  - @categories.each do |category|
                    optgroup label=(category.name)
                    - category.tests.each do |test|
                      option value="#{test.id}"  #{test.name}

            - if flash[:year]
              .form-group.field_with_errors
                label.col-sm-3.control-label Year of birth
                .col-sm-9
                  = number_field_tag "year", '', placeholder: 'Enter year of birth', class: 'form-control'
                  span class="error"
                    = flash[:year]

            - else
              .form-group
                label.col-sm-3.control-label Year of birth
                .col-sm-9
                  = number_field_tag "year", '', placeholder: 'Enter year of birth', class: 'form-control'

            = button_to "Create Report", nil, :class => 'btn btn-primary pull-right'
            .clearfix

    .col-sm-6
      .well
        h2.text-center
          span.glyphicon.glyphicon-th-list
          span  Compare Scores
        hr
        .well
          = form_tag(compare_players_path, method: 'post', id: "compare_players", class: "form-horizontal")
            .form-group
              label.col-sm-3.control-label Select Test
              .col-sm-9
                select#tests name="test" class="form-control"
                  - @categories.each do |category|
                    optgroup label=(category.name)
                    - category.tests.each do |test|
                      option value="#{test.id}"  #{test.name}

            .form-group
              label.col-sm-3.control-label Select player
              .col-sm-9
                select#player_1 name="player_1" class="form-control"
                  - @account.teams.each do |team|
                    optgroup label=(team.name)
                    - team.players.each do |player|
                      option value="#{player.id}"  #{player.full_name}

            .form-group
              label.col-sm-3.control-label Select player to compare
              .col-sm-9
                select#player_2 name="player_2" class="form-control"
                  - @account.teams.each do |team|
                    optgroup label=(team.name)
                    - team.players.reverse.each do |player|
                      option value="#{player.id}" #{player.full_name}
            hr
            hr
            .col-md-12
              = button_to "Compare Scores", nil, :class => 'btn btn-primary pull-right'
          .clearfix

javascript:
  $(document).ready(function(){
    $('#player_1').change(function(){
      $('#player_2 option').prop('disabled', false);
      $('#player_2 option[value="'+ $(this).val() +'"]').prop('disabled', true);
    });
    $('#player_2').change(function(){
      $('#player_1 option').prop('disabled', false);
      $('#player_1 option[value="'+ $(this).val() +'"]').prop('disabled', true);
    });
  });

app/views/users/coach_profile.html.slim
h1 Coach Control Panel
.row
  .col-sm-6
    .well
      h2.text-center.text-red
        span.glyphicon.glyphicon-paperclip
        span  View Soccer Skills Challenges
      hr
      = link_to "View", categories_path, class: "btn btn-primary pull-right"
      .clearfix
  .col-sm-6
    .well
      h2.text-center.text-red
        span.glyphicon.glyphicon-paperclip
        span  View Weekly Session Plans
      hr
      = link_to "View", session_plan_categories_path, class: "btn btn-primary pull-right" 
      .clearfix
  .col-sm-6
  .well
    h2.text-center.text-red
      span.glyphicon.glyphicon-paperclip
      span  Skills Library
    hr
    = link_to "View", session_plan_categories_path, class: "btn btn-primary pull-right" 
    .clearfix
.row
  .col-sm-6
    .well
      h2.text-center.text-red
        span.glyphicon.glyphicon-plus
        span  Add Test Scores
      .well
        = form_tag(scores_path, class: "form-horizontal")
          .form-group
            label.col-sm-3.control-label Select Team
            .col-sm-9
              = select_tag "teams", options_from_collection_for_select(@account.teams, :id, :name), {class: 'form-control'}
            
          .form-group
            label.col-sm-3.control-label Select Test
            .col-sm-9
              select#tests name="tests" class="form-control"
                - @categories.each do |category|
                    optgroup label=(category.name)
                    - category.tests.each do |test|
                        option value="#{test.id}"  #{test.name}
          hr
          hr
          = button_to "Add Scores", nil, :class => 'btn btn-primary pull-right'
          .clearfix
          
  .col-sm-6
    .well
      h2.text-center.text-red 
        span.glyphicon.glyphicon-th-list
        span  Create Reports
      .well
        = form_tag(coach_report_path, method: 'post', id:"show_players", class: "form-horizontal")
          .form-group
            label.col-sm-3.control-label Select Team
            .col-sm-9
              = select_tag "teams", options_from_collection_for_select(@account.teams, :id, :name), class: 'form-control chosen-select', multiple: true
              
          .form-group
            label.col-sm-3.control-label Choose Date
            .col-sm-9
              = select_tag "date", options_for_select(['Today', 'Last 7 Days', 'This Month', 'All Time'], params[:date]), {class: 'form-control'}
            
          .form-group
            label.col-sm-3.control-label Select Test
            .col-sm-9
              select#tests name="tests" class="form-control"
                - @categories.each do |category|
                    optgroup label=(category.name)
                    - category.tests.each do |test|
                        option value="#{test.id}"  #{test.name}

          = button_to "Create Report", nil, :class => 'btn btn-primary pull-right'
          .clearfix

app/views/users/edit.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
- if current_user.coach?
  = link_to t('.new', :default => t("helpers.links.new")), new_user_path(session[:account]), :class => 'btn btn-primary'
- else
  = link_to t('.new', :default => t("helpers.links.new")), new_user_path(session[:account]), :class => 'btn btn-primary'

table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:first_name)
      th= model_class.human_attribute_name(:last_name)
      th= model_class.human_attribute_name(:type)
      th= model_class.human_attribute_name(:email)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @users.each do |user|
      tr
        td= link_to user.id, user_path(user)
        td= user.first_name
        td= user.last_name
        td= Role.key_for(user.type_user)
        td= user.email
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_destroy_user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
          

app/views/users/new.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => "Welcome, " + @user.full_name

p  
  -if @user.standard? && @user.has_players?
    table class= "table table-striped"
      thead
        tr
          th= "Link to player page"
          th= "Most recent score"
      tbody  
      - @user.players.each do |player|
  	    tr
          td= link_to player.full_name, player_path(player), :class => 'btn btn-default'
          -unless player.scores.empty?
            td= player.scores.last.test.name + ": " + player.scores.last.value.to_s

p
  strong= model_class.human_attribute_name(:type_user) + ':'
  br
  = Role.key_for(@user.type_user)
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @user.email

= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
'
-unless current_user.standard?
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'