config/routes.rb
SoccerApp::Application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  scope "/admin" do
    resources :users
    match 'users/:id/delete' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end

  resources :accounts do
    resources :teams
    resources :locations
    get "report" => 'accounts#report', as: :report
  end

  resources :categories do
    resources :tests
  end

  resources :session_plan_categories do
     resources :session_plans
  end

  resources :players 
  
  resources :test do
    resources :scores
  end

  post 'manage_scores' => 'scores#manage', as: :manage_scores
  post 'scores' => 'scores#index', as: :scores
  get 'coach/:id' => 'users#coach_profile', as: :coach
  get 'coach_admin/:id' => 'users#coach_admin_controls', as: :coach_admin
  get 'account_error' => 'users#account_error', as: :account_error
  get 'account_select' => 'users#account_select', as: :account_select
  get '/player/history/:id/:test_id' => 'players#history', as: :player_history
  post '/player/coach_report/' => 'players#coach_report', as: :coach_report
  post '/players/compare_players/' => 'players#compare_players', as: :compare_players
  post '/players/import/' => 'players#import', as: :players_import
  post '/players/search/' => 'players#search', as: :players_search
  get '/player/:id/players_scores' => 'players#players_scores', as: :players_scores

  post 'teams/report' => 'teams#team_report', as: :team_report
  post 'tests/report' => 'tests#tests_report', as: :tests_report

end

app/views/shared/_admin_navbar.html.slim
= render 'shared/coach_navbar'
li.dropdown
  a.dropdown-toggle data-toggle="dropdown" href="#" 
    | Users
    b.caret
  ul.dropdown-menu
    li
      = link_to 'Manage Accounts', accounts_path
    li.divider
    li
      = link_to 'Manage all Users', users_path
    li
      = link_to 'Manage all Players', players_path

app/views/shared/_coach_navbar.html.slim
/li.dropdown
  a.dropdown-toggle data-toggle="dropdown" href="#" 
    | Teams
    b.caret
  ul.dropdown-menu
    li
      = link_to 'Add a new Team', new_account_team_path(@account)
    li
      = link_to 'View/Manage my Teams', account_teams_path(@account)
/li.dropdown
  a.dropdown-toggle data-toggle="dropdown" href="#" 
    | Tests and Scores
    b.caret
  ul.dropdown-menu
    li
      = link_to 'View available Test Categories', categories_path
    li
      = link_to 'Add a new Test Category', new_category_path
    li.divider  
/    li
      = link_to 'Add a new Test', new_test_path
/    li
      = link_to 'Add Scores for a test', choose_test_for_scores_path
/- if current_user.session_plans_visible?
  li.dropdown
    a.dropdown-toggle data-toggle="dropdown" href="#" 
      | Session Plans
      b.caret
    ul.dropdown-menu
      li
        = link_to 'View available Categories for Session Plans', session_plan_categories_path 
      li.divider
      li
        = link_to 'Add a new Category for Session Plans', new_session_plan_category_path
/      li
        = link_to 'Add a new Session Plan', new_session_plan_path
/li.dropdown
  a.dropdown-toggle data-toggle="dropdown" href="#" 
    | Players
    b.caret
  ul.dropdown-menu
    li
      = link_to 'Manage my players', players_path 
    li.divider
    li
      = link_to 'Add a new Player', new_player_path
/    li
      = link_to 'Import Players via CSV', players_import_path
/li.dropdown
  a.dropdown-toggle data-toggle="dropdown" href="#" 
    | Scores
    b.caret
  ul.dropdown-menu
    li
      = link_to "Review my teams' scores", scores_path
/   li
      = link_to 'Add new Scores', new_score_path
      
- if session[:account].nil?
  li
    = link_to "Select account", account_select_path
- else
  li= link_to "Coach Control Panel", coach_path(session[:account].id)
  li= link_to "Admin Control Panel", coach_admin_path(session[:account].id)
  

app/views/shared/_player_navbar.html.slim
li.dropdown
  a.dropdown-toggle data-toggle="dropdown" href="#" 
    | Admin Controls
    b.caret
  ul.dropdown-menu
    li
      = link_to 'Manage my Accounts', accounts_path
    li.divider
    li
      = link_to 'Manage all Users', users_path
    li
      = link_to 'Manage all Players', players_path