config/routes.rb
SoccerApp::Application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  scope "/admin" do
    resources :users
    match 'users/:id/delete' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end

  resources :accounts do
    resources :teams
    resources :locations
    get "report" => 'accounts#report', as: :report
  end

  resources :categories do
    resources :tests
  end

  resources :session_plan_categories do
     resources :session_plans
  end

  resources :players 
  
  resources :test do
    resources :scores
  end

  post 'manage_scores' => 'scores#manage', as: :manage_scores
  post 'scores' => 'scores#index', as: :scores
  get 'coach/:id' => 'users#coach_profile', as: :coach
  get 'coach_admin/:id' => 'users#coach_admin_controls', as: :coach_admin
  get 'account_error' => 'users#account_error', as: :account_error
  get 'account_select' => 'users#account_select', as: :account_select
  get '/player/history/:id/:test_id' => 'players#history', as: :player_history
  post '/player/coach_report/' => 'players#coach_report', as: :coach_report
  post '/players/compare_players/' => 'players#compare_players', as: :compare_players
  post '/players/import/' => 'players#import', as: :players_import
  post '/players/search/' => 'players#search', as: :players_search
  get '/player/:id/players_scores' => 'players#players_scores', as: :players_scores

  post 'teams/report' => 'teams#team_report', as: :team_report
  post 'tests/report' => 'tests#tests_report', as: :tests_report

end

app/models/player.rb
class Player < ActiveRecord::Base
  
  has_and_belongs_to_many :teams
  belongs_to :user
  has_many :scores
  has_many :tests, :through => :scores
  
  validates_presence_of :user, :first_name, :last_name, :birthday, :teams
  
  before_save :change_birth_year
  
  def full_name
    "#{first_name} #{last_name}".titleize
  end

  def age
    ((DateTime.now - birthday) / 365.25).to_i
  end

  def year_of_birth
    birthday.year
  end
  
  def change_birth_year
    if self.birthday.year < 1920
      self.birthday += 2000.years
    end
  end

  def list_teams
    str = ""
    teams.each do |team|
      str += team.name + ", "
    end
    return str[0..str.length-3]
  end
  
  def high_time_score(test_id, date)
    # sql = "select min(to_char(to_timestamp(value) AT TIME ZONE 'UTC','HH24:MI:SS')) as time from scores where player_id = #{id} and test_id = #{test_id}"
    # self.connection.execute(sql).to_a[0]["time"]
    if date.eql? 'Today'
      date = 24.hours.ago
    elsif date.eql? 'Last 7 Days'
      date = 7.days.ago
    elsif date.eql? 'This Month'
      date = (Time.now().day - 1).days.ago
    else
      date = 100.years.ago
    end

    Time.at(get_score_test(test_id).where('updated_at > ? ', date).minimum("value")).strftime("%H:%M:%S")
  end
  
   def low_time_score(test_id, date)
    # sql = "select min(to_char(to_timestamp(value) AT TIME ZONE 'UTC','HH24:MI:SS')) as time from scores where player_id = #{id} and test_id = #{test_id}"
    # self.connection.execute(sql).to_a[0]["time"]
    if date.eql? 'Today'
      date = 24.hours.ago
    elsif date.eql? 'Last 7 Days'
      date = 7.days.ago      
    elsif date.eql? 'This Month'
      date = (Time.now().day - 1).days.ago
    else
      date = 100.years.ago
    end

    Time.at(get_score_test(test_id).where('updated_at > ? ', date).maximum("value")).strftime("%H:%M:%S")
  end 

  def high_numeric_score(test_id, date)
    if date.eql? 'Today'
      time = 24.hours.ago
    elsif date.eql? 'Last 7 Days'
      time = 7.days.ago
    elsif date.eql? 'This Month'
      time = (Time.now().day - 1).days.ago
    else
      time = 100.years.ago
    end
    scores = get_score_test(test_id).where('updated_at > ?', time)
    if scores.empty?
      nil
    else
      scores.maximum("value").to_f
    end
  end
  
    def low_numeric_score(test_id, date)
    if date.eql? 'Today'
      time = 24.hours.ago
    elsif date.eql? 'Last 7 Days'
      time = 7.days.ago
    elsif date.eql? 'This Month'
      time = (Time.now().day - 1).days.ago
    else
      time = 100.years.ago
    end

    scores = get_score_test(test_id).where('updated_at > ?', time)
    if scores.empty?
      nil
    else
      scores.minimum("value").to_f
    end
  end
  
#Todo
  def pos_age_rank_numeric(test_id, age)
    sql = "select * from (SELECT row_number() OVER (order by avg(s.value) DESC) as pos, EXTRACT(year from AGE(NOW(), u.birthday)) as age, u.first_name as name, avg(s.value) as average, t.id as test_id, u.id as player_id from players u, scores s, tests t where s.player_id = u.id and s.test_id = t.id and t.id = #{test_id} and EXTRACT(year from AGE(NOW(), u.birthday)) = #{age} group by u.birthday, u.first_name, t.id, u.id) as h where player_id = #{id};"
    connection.execute(sql).to_a[0]["pos"]
  end

#Todo
  def pos_age_rank_time(test_id, age)
    sql = "select * from (SELECT row_number() OVER (order by to_char(to_timestamp(avg(s.value)) AT TIME ZONE 'UTC','HH24:MI:SS') ASC) as pos, EXTRACT(year from AGE(NOW(), u.birthday)) as age, u.first_name as name, to_char(to_timestamp(avg(s.value)) AT TIME ZONE 'UTC','HH24:MI:SS') as average, t.id as test_id, u.id as player_id from players u, scores s, tests t where s.player_id = u.id and s.test_id = t.id and t.id = #{test_id} and EXTRACT(year from AGE(NOW(), u.birthday)) = #{age} group by u.birthday, u.first_name, t.id, u.id) as h where player_id = #{id};"
    result = connection.execute(sql).to_a[0]["pos"]
  end

#Todo
  def pos_overall_time_rank(test_id)
    sql = "SELECT * from (SELECT row_number() OVER (order by to_char(to_timestamp(avg(value)) AT TIME ZONE 'UTC','HH24:MI:SS') ASC) as pos, to_char(to_timestamp(avg(value)) AT TIME ZONE 'UTC +4:30','HH24:MI:SS'), player_id from scores where test_id = #{test_id} group by player_id) as h where player_id = #{id};"
    connection.execute(sql).to_a[0]["pos"]
    
  end

#Todo
  def pos_overall_numeric_rank(test_id)
    sql = "SELECT * FROM (SELECT row_number() OVER (order by avg(value) DESC) as pos, avg(value), player_id from scores where test_id = #{test_id} group by player_id) as h where player_id = #{id};"
    connection.execute(sql).to_a[0]["pos"]
  end

  def has_scores?(test_id)
    get_score_test(test_id).count > 0
  end

  def get_score_test(test_id)
    scores.where("test_id = ?", test_id)
  end

  def average_scores(test_id)
    get_score_test(test_id).average(:value)
  end

#Todo
  def user_for_age
    #sql = "SELECT * FROM (SELECT EXTRACT(year from AGE(NOW(), birthday)) as age from players) as h where age = #{age}"
    sql = "SELECT * FROM players p WHERE EXTRACT(YEAR FROM p.birthday) = #{year_of_birth}"
    connection.execute(sql).to_a
  end

  def age_average_numeric(test_id)
    sql = "SELECT avg(s.value) as average from scores s, players p where s.test_id = #{test_id} and s.player_id = p.id and EXTRACT(year from AGE(NOW(), p.birthday)) = #{age}"
    connection.execute(sql).to_a[0]["average"].to_f.round(2)
  end

  def age_average_time(test_id)
    sql = "SELECT to_char(to_timestamp(avg(s.value)) AT TIME ZONE 'UTC','HH24:MI:SS') as average from scores s, players p where s.test_id = #{test_id} and s.player_id = p.id and EXTRACT(year from AGE(NOW(), p.birthday)) = #{age}"
    connection.execute(sql).to_a[0]["average"]
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :check_user_type, only: [:edit, :index, :destroy, :new, :create, :update, :import]

  def show
    @player = Player.find(params[:id])
    @categories = Category.all
  end

  def history
    @player = Player.find(params[:id])
    @scores = @player.scores.where(:test_id => params[:test_id]).order('created_at')
  end
  
  def index
    if current_user.standard?
      redirect_to root
    elsif !session[:account].nil?
      @account = session[:account]
      @players = (Player.joins(:teams).where("account_id = ?", @account.id).order(:last_name)).uniq
    elsif current_user.admin?
      @players = Player.all.order(:last_name)
    else
      redirect_to account_select_path
    end
  end

  def new
    if current_user.standard?
      @player = current_user.players.new
    else
      @player = Player.new
    end
    if current_user.coach?
      @account = session[:account]
      @teams = @account.teams
      @users = @account.users
    else
      @account = Account.all
      @teams = Team.all
      @users = User.all
    end
  end
  
  def create
    @user = User.find_by(:email => params[:user_email]) 
    if @user.nil?
      @user = User.new
      @user.email = params[:user_email]
      @user.password = "12345678"
      @user.password_confirmation = "12345678"
      @user.first_name = params[:first_name]
      @user.last_name = params[:last_name]
      @user.accounts << session[:account] unless session[:account].nil?
      @user.type_user = Role::STANDARD
      @user.save!
    end
    @player = @user.players.new(player_params_create)
    @player.team_ids = params[:teams]
    @player.birthday = Date.new params[:birthday]['(1i)'].to_i, params[:birthday]['(2i)'].to_i, params[:birthday]['(3i)'].to_i

    if @player.save
      #NotificationMailer.notification_new_player(@user, current_user).deliver
      #NotificationMailer.notification_to_player(@user).deliver
      if session[:account].nil?
        redirect_to players_path, notice: "Players created successfully."
      else
        redirect_to coach_path(session[:account]), notice: "Player created successfully."  
      end
      
    else
      render 'new'
    end
  end

  def edit
    if current_user.coach?
      if session[:account].nil?
        redirect_to account_select_path, notice: "Please select which account you're acting under first."
      else
        @teams = session[:account].teams
        @player = Player.find(params[:id])
        @users = User.standard
      end
    elsif current_user.admin?
      @teams = Team.all
      @player = Player.find(params[:id])
      @users = User.standard
    else
      redirect_to root_path, notice: "You do not have the required permissions to edit this player.  Please contact your coach or an administrator."
    end
      
  end
  
  def update
    @player = Player.find(params[:id])
    @player.user = User.find(params[:player][:user_id])
    @player.team_ids = nil
    params[:teams].each do |team_id|
      team = Team.find(team_id)
      @player.teams << team
    end
    @player.birthday = Date.new params[:birthday]['(1i)'].to_i, params[:birthday]['(2i)'].to_i, params[:birthday]['(3i)'].to_i
    if @player.update(player_params_update)
      redirect_to player_path(@player), :notice => "Player updated successfully"
    else
      render 'edit'
    end
  end

  def coach_report
    @test = Test.find(params[:tests])
    ps = Hash.new
    @position_average = Hash.new
    if !params[:teams].nil?
      params[:teams].each do |team_id|
        team = Team.find_by(id: team_id)
        team.players.each do |player|
          if player.has_scores?(@test.id)
            if @test.time?
              score = player.high_time_score(@test.id, params[:date])
              unless score.nil?
                ps[player.full_name] = [score, team.name, player.birthday.year]
              end
            else
              score = player.high_numeric_score(@test.id, params[:date])
              unless score.nil?
                ps[player.full_name] = [score, team.name, player.birthday.year]
              end
            end
          end
        end
        @position_average[team.name] = [@test.type_unit == Unit::TIME ? team.team_system_rank_time(@test.id) : team.team_system_rank_numeric(@test.id).to_i.ordinalize, @test.type_unit == Unit::TIME ? team.team_average_time(@test.id) : team.team_average_numeric(@test.id)]
      end
    end
    @players_scores = Hash[ps.sort_by{|k,v| v}.reverse]
  end

  def compare_players
    if params[:player_1].nil? || params[:player_2].nil? || params[:test].nil?
      redirect_to :back
    else
      @player = Player.find(params[:player_1])
      @player_compare = Player.find(params[:player_2])
      @test = Test.find(params[:test])
    end
  end

  def import

    csv_text = params[:csv_players].read
    csv = CSV.parse(csv_text, :headers => true, :force_quotes => true)
    csv.each do |row|
      user = User.find_by(:email => row['email'].downcase)
      if user.nil?
        puts row['email'].downcase!
        user = User.new
        user.first_name = row['first name'].capitalize
        user.last_name = row['last name'].capitalize
        user.email = row['email']
        user.password = '12345678'
        user.password_confirmation = '12345678'
        user.type_user = Role::STANDARD
        user.save!
      end
      
      
      player = user.players.new
      player.first_name = row['first name'].capitalize
      player.last_name = row['last name'].capitalize
           
      if user.players.count > 0
        user.players.each do |existing_player|
          if existing_player.full_name.downcase == player.full_name.downcase
            player = existing_player
            break
          end
        end
      end
      
      #CSV will overwrite birthdays but not names because I'm currently using names as the searchable field
      player.birthday = row['birthday'].to_date
      
      #Assign teams.  Will not overwrite old teams and will not duplicate teams.
      params[:teams].each do |team_id|
        team = Team.find(team_id)
        unless player.teams.include? team
          player.teams << team
        end
      end

      player.save!

    # csv.each do |row|
      # @user = User.where(:email => row['email']).first
      # if @user
        # puts "Ya tenemos al #{@user.inspect}"
        # params["teams"].each do |team_id|
          # t = Team.find(team_id)
          # @user.teams << t
          # puts "grabo #{@user.save}"
          # puts @user.teams.inspect
        # end
      # else
        # @user = User.new
        # @user.team_ids = params[:teams]
        # @user.first_name = row['first name']
        # @user.last_name = row['last name']
        # @user.birthday = Date.civil(row['birthday'].to_i, 1,1)
        # @user.email = row['email']
        # @user.password = "12345678"
        # @user.password_confirmation = "12345678"
        # @user.type_user = Role::PLAYER
        # @user.save
      # end
    # end
    
    end

    redirect_to coach_path(session[:account]), notice: "Players created successfully."
  end

  def destroy
    player = Player.find(params[:id]).destroy
    flash[:notice] = "Player " + player.full_name + " deleted."
    redirect_to players_path 
  end
  
  def search
    @player = Player.find(params[:player])
    @categories = Category.all
    @rank_age = @player.user_for_age.count
    @overall_rank = Player.count
    render 'players_scores'
  end
  
  def players_scores
    @player = Player.find(params[:id])
    @categories = Category.all
    @rank_age = @player.user_for_age.count
    @overall_rank = Player.count
  end
  
  private
  
  def player_params_create
    params.permit(:teams, :first_name, :last_name, :birthday, :user_id)
  end

  def player_params_update
    params.require(:player).permit(:first_name, :last_name, :user_id)
  end
  
  def check_user_type
    if current_user.standard?
      redirect_to root_path, notice: "You do not have the permissions to do that action."
    end
  end
  
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.slim
- content_for :head do
  = javascript_include_tag "manage_fields.js"
= form_for @player, :html => { :class => "form-horizontal" } do |f|
 
  - unless @player.nil? 
    - unless @player.errors.empty?
      ul.form-errors
        - @player.errors.full_messages.each do |message|
            li= message
  
  .form-group
    = f.label :first_name, :class => 'control-label'
    .controls
      = f.text_field :first_name, :class => 'form-control'
  .form-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'form-control'
  .form-group
    = label_tag :birthday, nil, :class => 'control-label'
    .controls
      = date_select :birthday, params[:birthday], {start_year: 1920, discard_month:false, discard_day:false, default:@player.birthday}, {:class => 'form-control'}
  .form-group
    = label_tag 'teams', nil, class: 'control-label'
    .controls
      = select_tag :teams, options_for_select(@teams.collect { |t| ["#{t.name} - #{t.account.name}", t.id]}, @player.team_ids), class: 'form-control chosen-select', multiple: true
  .form-group
    = f.label :user_id, class: 'control-label'
    .control
      = f.select :user_id, options_from_collection_for_select(@users, :id, :email, @player.user_id.to_s), class: 'form-control chosen-select', selected: @player.user_id.to_s
  
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), players_path, :class => 'btn'

app/views/players/_test_category_table.html.slim
h3= "#{category.name.titleize} Tests"
table class="table table-striped"
  thead
    tr
      th Test name
      th Low Score
      th High Score
      th Age Average
      th Age Rank
      th Overall Rank
      th History
  tbody
    - if category.tests.count > 0
        = render partial: 'test_content_table', collection: category.tests, as: :test
    - else
        tr
          td.text-center colspan="7" No found Tests

app/views/players/_test_content_table.html.slim
tr
  -if @player.has_scores?(test.id)
    td= "#{test.name}"
    - if test.time?
        td= @player.low_time_score(test.id, 'All Time')
        td= @player.high_time_score(test.id, 'All Time')
        td= @player.age_average_time(test.id)
        td= "#{@player.pos_age_rank_time(test.id, @player.age)} / #{test.players.uniq.select{|p| p.age == @player.age}.count}"
        td= "#{@player.pos_overall_time_rank(test.id)} / #{test.players.uniq.count}"
        td= link_to "HISTORY", player_history_path(@player.id, test.id), class: "btn btn-sm btn-info"

    - else
        td= @player.low_numeric_score(test.id, 'All Time')
        td= @player.high_numeric_score(test.id, 'All Time')
        td= @player.age_average_numeric(test.id)
        td= "#{@player.pos_age_rank_numeric(test.id, @player.age)} / #{test.players.uniq.select{|p| p.age == @player.age}.count}"
        td= "#{@player.pos_overall_numeric_rank(test.id)} / #{test.players.uniq.count}"
        td= link_to "HISTORY", player_history_path(@player.id, test.id), class: "btn btn-sm btn-info"

app/views/players/coach_report.html.slim
- content_for :head do
  = javascript_include_tag "report.js"

= hidden_field_tag "test_name", "#{@test.name} Test"
.page-header
  h1 
    small  ="#{@test.name} Test"

table class="table table-striped datetable"
  thead
    tr
      th Position
      th Player Name
      th Player Birth Year
      th Score
      th Team
  tbody
    - @players_scores.each_with_index do |player, index|
      -unless player.nil?
        tr
          td= index + 1
          td= player[0]
          td= player[1][2]
          - if @test.time?
              td= Time.parse(player[1][0]).strftime("%H:%M:%S")
          - else
              td= player[1][0].round(2)
          td= player[1][1]
/.col-sm-12
  /- @position_average.each do |key, value|
    /.col-sm-12
      /h1 =key
    /.col-sm-6
      /.well
        /h3 = "Team Average Score = #{value[1]}"
    /.col-sm-6
      /.well
        /h3= "Team Rank In System = #{value[0]} Position"

app/views/players/compare_players.html.slim
.col-sm-12
.page-header
  h1 
    | Compare Scores
    small  - #{@test.name} Test

.col-sm-6
  h1 = @player.full_name
  ul.list-group
  - if @player.has_scores?(@test.id)
      - if @test.time?
          li.list-group-item
            span.badge style="font-size:16px"= @player.high_time_score(@test.id, 'All Time')
            | High Score
          - @player.teams.each do |t| 
              li.list-group-item
                span.badge style="font-size:16px"= t.team_average_time(@test.id)
                | Team #{t.name}
          li.list-group-item
            span.badge style="font-size:16px"= @player.pos_age_rank_time(@test.id, @player.age).to_i.ordinalize
            | Age Rank
          li.list-group-item
            span.badge style="font-size:16px"= @player.pos_overall_time_rank(@test.id).to_i.ordinalize
            | Overall Rank
      - else
          li.list-group-item
            span.badge style="font-size:16px"= @player.high_numeric_score(@test.id, 'All Time')
            | High Score
          - @player.teams.each do |t| 
              li.list-group-item
                span.badge style="font-size:16px"= t.team_average_numeric(@test.id)
                | Team #{t.name}
          li.list-group-item
            span.badge style="font-size:16px"= @player.pos_age_rank_numeric(@test.id, @player.age).to_i.ordinalize
            | Age Rank
          li.list-group-item
            span.badge style="font-size:16px"= @player.pos_overall_numeric_rank(@test.id).to_i.ordinalize
            | Overall Rank
  - else
      .well
        | No found result for this test
.col-sm-6
  h1 = @player_compare.full_name
  ul.list-group
  - if @player_compare.has_scores?(@test.id)
      - if @test.time?
          li.list-group-item
            span.badge style="font-size:16px"= @player_compare.high_time_score(@test.id, 'All Time')
            | High Score
          - @player_compare.teams.each do |t| 
              li.list-group-item
                span.badge style="font-size:16px"= t.team_average_time(@test.id)
                | Team #{t.name}
          li.list-group-item
            span.badge style="font-size:16px"= @player_compare.pos_age_rank_time(@test.id, @player_compare.age).to_i.ordinalize
            | Age Rank
          li.list-group-item
            span.badge style="font-size:16px"= @player_compare.pos_overall_time_rank(@test.id).to_i.ordinalize
            | Overall Rank
      - else
          li.list-group-item
            span.badge style="font-size:16px"= @player_compare.high_numeric_score(@test.id, 'All Time')
            | High Score
          - @player_compare.teams.each do |t| 
              li.list-group-item
                span.badge style="font-size:16px"= t.team_average_numeric(@test.id)
                | Team #{t.name}
          li.list-group-item
            span.badge style="font-size:16px"= @player_compare.pos_age_rank_numeric(@test.id, @player_compare.age).to_i.ordinalize
            | Age Rank
          li.list-group-item
            span.badge style="font-size:16px"= @player_compare.pos_overall_numeric_rank(@test.id).to_i.ordinalize
            | Overall Rank
  - else
      .well
        | No found result for this test

app/views/players/edit.html.slim
- model_class = Player
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

= link_to 'Show', @player, :class => 'btn btn-small'
'|
= link_to 'Back', players_path, :class => 'btn btn-small'

app/views/players/history.html.slim
div class="page-header"
  h1 
    =@player.full_name
    small  Test History


table class="table table-striped"
  thead
    tr
      th Test
      th Score
      th Test Day
  tbody
    - @scores.each do |score|
      tr
        td= score.test.name
        td= score.test.numeric? ? score.value.to_f : Time.at(score.value).strftime("%H:%M:%S")
        td= score.created_at.strftime("%A, %B %d %Y")

app/views/players/index.html.slim
.page-header
  -if @account.nil?
    h1= "All Players"
  -else
    h1= "Players for " + @account.name

- if current_user.coach?
  = link_to t('.new', :default => t("helpers.links.new")), new_player_path(session[:account]), :class => 'btn btn-primary'
- else
  = link_to t('.new', :default => t("helpers.links.new")), new_player_path(session[:account]), :class => 'btn btn-primary'
table class= 'table table-striped'
  thead
    tr
      th Name
      th Teams
      th colspan=3 Controls
  
  -@players.each do |player|
    tr
      td= player.full_name
      td= player.list_teams
      td= link_to 'View Scores', players_scores_path(player), class: 'btn btn-info btn-xs'
      td= link_to 'Edit', edit_player_path(player), class: 'btn btn-default btn-xs'
      td= link_to 'Delete', player_path(player), method: :delete, class: 'btn btn-danger btn-xs', confirm: 'Are you sure?'
  

app/views/players/new.html.slim
.page-header
  h1 Add New Player
= form_tag("/players", method: 'post', id: 'add_player' , class: 'form-horizontal') do
 
  - unless @player.errors.empty?
    ul.form-errors
      - @player.errors.full_messages.each do |message|
        li= message

  .form-group
    = label_tag 'teams', nil, class: 'control-label'
    .controls
      = select_tag :teams, options_from_collection_for_select(@teams, :id, :name, params[:teams]), class: 'form-control chosen-select', multiple: true, "data-placeholder" => "Please select the Player's Team", :required => true
  .form-group
    = label_tag :first_name, nil, :class => 'control-label'
    .controls
      = text_field_tag :first_name, params[:first_name],  :class => 'form-control', :required => true
  .form-group
    = label_tag :last_name, nil, :class => 'control-label'
    .controls
      = text_field_tag :last_name, params[:last_name],  :class => 'form-control', :required => true
  .form-group
    = label_tag :birthday, nil, :class => 'control-label'
    .controls
      = date_select :birthday, params[:birthday], {start_year: 1920, discard_month:false, discard_day:false}, {:class => 'form-control'}
  .form-group
    = label_tag :user_email, 'Email of the user this player is being classified under', :class => 'control-label'
    .controls
      = text_field_tag :user_email, params[:user_email], :class => 'form-control'
	    
  = button_to "Create Player", nil, :class => 'btn btn-primary'

app/views/players/players_scores.html.slim
div class="page-header"
  h1 
    =@player.full_name
    small  Scores Information        
  
= render partial: 'test_category_table', collection: @categories, as: :category

=link_to "Back", player_path(@player), class: 'btn btn-info text-right'
        

app/views/players/show.html.slim
div class="page-header"
  h1 
    =@player.full_name
    small  Home         
    =link_to "Player's User", user_path(@player.user), class: 'btn btn-info text-right'
.row
  .col-sm-6
    .well
      h2.text-center
        span.glyphicon.glyphicon-star-empty
        span  View Scores
      hr
      .well
        = link_to players_scores_path(@player), class: "btn btn-primary btn-lg btn-block" do
          span  View Scores

  .col-sm-6
    .well
      h2.text-center
        span.glyphicon.glyphicon-bookmark
        span  View Challenges
      hr
      .well
        = link_to categories_path, class: "btn btn-primary btn-lg btn-block" do
          span  Challenges
          
.row
  .col-sm-6
    .well
      h2.text-center 
        span.glyphicon.glyphicon-star-empty
        span  Compare Scores
      hr
      .well
        = form_tag(compare_players_path, method: 'post', id:"compare_players", class: "form-horizontal")
          .form-group
            label.col-sm-3.control-label Select Test
            .col-sm-9
              select#tests name="test" class="form-control"
                - @categories.each do |category|
                    optgroup label=(category.name)
                    - category.tests.each do |test|
                        option value="#{test.id}"  #{test.name}

          .form-group
            label.col-sm-3.control-label Select Player
            .col-sm-9
              select#tests name="player_compare" class="form-control"
                - @player.teams.each do |team|
                    optgroup label=(team.name)
                    - team.players.each do |player|
                      - unless player.id == @player.id
                          option value="#{player.id}"  #{player.full_name}

            .form-group
              = hidden_field_tag 'player', @player.id
          hr
          = button_to "Compare Scores", nil, :class => 'btn btn-primary pull-right'
          .clearfix

  .col-sm-6
    .well
      h2.text-center 
        span.glyphicon.glyphicon-pencil
        span  Create A Report
      hr
      .well
        = form_tag(coach_report_path, method: 'post', id:"show_players", class: "form-horizontal")
          .form-group
            label.col-sm-3.control-label Select Team
            .col-sm-9
              = select_tag "teams", options_from_collection_for_select(@player.teams, :id, :name), class: 'form-control chosen-select', multiple: true
              
          .form-group
            label.col-sm-3.control-label Choose Date
            .col-sm-9
              = select_tag "date", options_for_select(['Today', 'Last 7 Days', 'This Month', 'All Time'], params[:date]), {class: 'form-control'}
            
          .form-group
            label.col-sm-3.control-label Select Test
            .col-sm-9
              select#tests name="tests" class="form-control"
                - @categories.each do |category|
                    optgroup label=(category.name)
                    - category.tests.each do |test|
                        option value="#{test.id}"  #{test.name}
          = button_to "Create Report", nil, :class => 'btn btn-primary pull-right'
          .clearfix