config/routes.rb
SoccerApp::Application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  scope "/admin" do
    resources :users
    match 'users/:id/delete' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  end

  resources :accounts do
    resources :teams
    resources :locations
    get "report" => 'accounts#report', as: :report
  end

  resources :categories do
    resources :tests
  end

  resources :session_plan_categories do
     resources :session_plans
  end

  resources :players 
  
  resources :test do
    resources :scores
  end

  post 'manage_scores' => 'scores#manage', as: :manage_scores
  post 'scores' => 'scores#index', as: :scores
  get 'coach/:id' => 'users#coach_profile', as: :coach
  get 'coach_admin/:id' => 'users#coach_admin_controls', as: :coach_admin
  get 'account_error' => 'users#account_error', as: :account_error
  get 'account_select' => 'users#account_select', as: :account_select
  get '/player/history/:id/:test_id' => 'players#history', as: :player_history
  post '/player/coach_report/' => 'players#coach_report', as: :coach_report
  post '/players/compare_players/' => 'players#compare_players', as: :compare_players
  post '/players/import/' => 'players#import', as: :players_import
  post '/players/search/' => 'players#search', as: :players_search
  get '/player/:id/players_scores' => 'players#players_scores', as: :players_scores

  post 'teams/report' => 'teams#team_report', as: :team_report
  post 'tests/report' => 'tests#tests_report', as: :tests_report

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tests
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :update, :edit]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: "category updated successfully."
    else
      render 'edit'
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_url, notice: "category created successfully."
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find_by(id: params[:id])
    @category.destroy

    redirect_to categories_url, notice: "category deleted."
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find_by(id: params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= form_for @category, :html => { :class => "form-horizontal" } do |f|
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn'

app/views/categories/edit.html.slim
- model_class = Category
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/index.html.slim
- model_class = Category
div class="page-header"
  h1 Test Categories
table class="table table-striped"
  thead
    tr
      - if current_user.admin?
        th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:tests)
      - if current_user.admin?
        th=t '.actions', :default => t("helpers.actions")
  tbody
    - @categories.each do |category|
      tr
        - if current_user.admin?
          td= link_to category.id, category_path(category)
        td= category.name
        td= link_to 'View Tests', category_tests_path(category), :class => 'btn btn-info'
        td
          - if current_user.admin?
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(category), :class => 'btn btn-default btn-xs'
              '
              = link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
              '

- if current_user.admin?
  = link_to t('.new', :default => t("helpers.links.new")), new_category_path, :class => 'btn btn-primary'

app/views/categories/new.html.slim
- model_class = Category
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/show.html.slim
- model_class = Category
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @category.name

= link_to t('.back', :default => t("helpers.links.back")), categories_path, :class => 'btn btn-default'
'
-if current_user.admin?
  = link_to t('.new', :default => t("helpers.links.new")), new_category_path, :class => 'btn btn-primary'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(@category), :class => 'btn btn-default'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(@category), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'



.row
  .col-6.w-col
	h2 Tests
	table class='table table-striped'
      thead
        tr
	      th Name
	      th Level
	      th File
	      th Link
	      - if current_user.admin?
	        th=t '.actions', :default => t("helpers.actions")
	  tbody
	    - @category.tests.order(:level).each do |test|
	      tr
	        td= test.name
	        td= Level.key_for(test.level)
	        td= link_to "Download Documentation", test.file.url, :target => ':_blank' if test.file?
	        td= link_to "Video link", test.link, :target => ":_blank" if test.link.nil?
	        td
	          - if current_user.admin?
	            = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_test_path(@category, test), :class => 'btn btn-default btn-xs'
	            '
	            = link_to t('.destroy', :default => t("helpers.links.destroy")), category_test_path(@category, test), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'